-- ==========================================================
-- REPORTING LAYER
-- ==========================================================


-- 1. FACT SALES VIEW
CREATE OR REPLACE VIEW VW_FACT_SALES AS
SELECT
    INVOICE,
    STOCKCODE,
    CUSTOMER_ID,
     CAST(INVOICEDATE AS DATE) AS INVOICEDATE,QUANTITY,
    PRICE AS UNIT_PRICE,
    (QUANTITY * PRICE) AS SALES_AMOUNT
    FROM CLEAN_TRANSACTIONS;

-- 2. DIM CUSTOMER VIEW
CREATE OR REPLACE VIEW VW_DIM_CUSTOMERS AS
WITH CUSTOMER_COUNTRY AS
(
    SELECT
        CUSTOMER_ID,
        COUNTRY,
        COUNT(*) AS ORDER_COUNT
    FROM CLEAN_TRANSACTIONS
    GROUP BY CUSTOMER_ID, COUNTRY
),
RANKED_COUNTRIES AS
(
    SELECT
        CUSTOMER_ID,
        COUNTRY,
        ORDER_COUNT,
        ROW_NUMBER() OVER (
            PARTITION BY CUSTOMER_ID
            ORDER BY ORDER_COUNT DESC, COUNTRY
        ) AS RN
    FROM CUSTOMER_COUNTRY
)
SELECT
    CUSTOMER_ID,
    COUNTRY
FROM RANKED_COUNTRIES
WHERE RN = 1
ORDER BY CUSTOMER_ID;

------------------------------------------------------------
-- 3. DIM PRODUCT VIEW
CREATE OR REPLACE VIEW VW_DIM_PRODUCTS AS
WITH PRODUCT_DESCRIPTION AS
(
    SELECT
        STOCKCODE,
        DESCRIPTION,
        COUNT(*) AS TRANSACTION_COUNT
    FROM CLEAN_TRANSACTIONS
    GROUP BY STOCKCODE, DESCRIPTION
),
RANKED_PRODUCTS AS
(
    SELECT
        STOCKCODE,
        DESCRIPTION,
        ROW_NUMBER() OVER
        (
            PARTITION BY STOCKCODE
            ORDER BY TRANSACTION_COUNT DESC, DESCRIPTION
        ) AS RN
    FROM PRODUCT_DESCRIPTION
)
SELECT
    STOCKCODE,
    DESCRIPTION
FROM RANKED_PRODUCTS
WHERE RN = 1
ORDER BY STOCKCODE;

-- 4. DIM DATE VIEW
CREATE OR REPLACE VIEW VW_DIM_DATE AS
WITH DATE_RANGE AS
(
    SELECT
        DATEADD(
            DAY,
            SEQ4(),
            (
                SELECT MIN(CAST(INVOICEDATE AS DATE))
                FROM CLEAN_TRANSACTIONS
            )
        ) AS DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 1000))
)
SELECT
    DATE,
    YEAR(DATE) AS YEAR,
    QUARTER(DATE) AS QUARTER,
    MONTH(DATE) AS MONTH_NUMBER,
    MONTHNAME(DATE) AS MONTH_NAME,
    WEEK(DATE) AS WEEK_NUMBER,
    DAY(DATE) AS DAY,
    DAYNAME(DATE) AS DAY_NAME
FROM DATE_RANGE
WHERE DATE <=
(
    SELECT MAX(CAST(INVOICEDATE AS DATE))   
    FROM CLEAN_TRANSACTIONS
)
ORDER BY DATE;

-- ==========================================================
-- END OF REPORTING LAYER
-- ==========================================================